name: "Check out code and lint source"
description: "Installs dependencies and runs common Python linters"
inputs:
  source:
    description: 'Source directory'
    required: false
  python-version:
    description: "What Python version use for running linting tools"
    required: false
    default: '3.8'
  use-isort:
    description: "Run isort check"
    required: false
    default: 'true'
  use-black:
    description: "Run black check"
    required: false
    default: 'true'
  use-flake8:
    description: "Run flake8 check"
    required: false
    default: 'true'
  use-mypy:
    description: "Run mypy check"
    required: false
    default: 'true'
  install-requirements:
    description: "Install dependencies from requirements.txt (for type checking)"
    required: false
    default: 'true'
  extra-requirements:
    description: "Install extra dependencies (type stubs, extensions etc.)"
    required: false
    default: ""
  working-directory:
    description: "Set working directory for lint-python"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
    - run: pip install lint-python==2.0.0
      shell: bash
    - run: pip install -r requirements.txt
      if: ${{inputs.install-requirements == 'true'}}
      shell: bash
    - run: lint-python --check --install
      working-directory: ${{inputs.working-directory}}
      shell: bash
branding:
  color: "green"
  icon: "check-square"
