name: "Check out code and lint source"
description: "Installs dependencies and runs common Python linters"
inputs:
  source:
    description: 'Source directory'
    required: true
  python-version:
    description: "What Python version use for running linting tools"
    required: false
    default: 3.8
  use-isort:
    description: "Run isort check"
    required: false
    default: true
  use-black:
    description: "Run black check"
    required: false
    default: true
  use-flake8:
    description: "Run flake8 check"
    required: false
    default: true
  use-mypy:
    description: "Run mypy check"
    required: false
    default: true
  install-requirements:
    description: "Install dependencies from requirements.txt (for type checking)"
    required: false
    default: true
  extra-requirements:
    description: "Install extra dependencies (type stubs, extensions etc.)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{inputs.python-version}}
    - run: pip install isort==5.10.1 black==22.3.0 flake8==3.8.4 mypy==0.940
      shell: bash
    - run: pip install -r requirements.txt
      if: ${{inputs.install-requirements == 'true'}}
      shell: bash
    - run: pip install ${{inputs.extra-requirements}}
      if: ${{inputs.extra-requirements != ''}}
      shell: bash
    - run: isort --check ${{inputs.source}}
      if: ${{inputs.use-isort == 'true'}}
      shell: bash
    - run: black --check ${{inputs.source}}
      if: ${{inputs.use-black == 'true'}}
      shell: bash
    - run: flake8 ${{inputs.source}}
      if: ${{inputs.use-flake8 == 'true'}}
      shell: bash
    - run: mypy --namespace-packages ${{inputs.source}}
      if: ${{inputs.use-mypy == 'true'}}
      shell: bash
branding:
  color: "green"
  icon: "check-square"
